function updateSoundGenToolbox(SyncOption, remote)
narginchk(0, 2);
if nargin < 1
    SyncOption = false;
end
if nargin < 2
    remote = 'origin';
end
mu.syncRepositories(...
    "log", '', ...
    "RepositoryPaths", fileparts(mfilename("fullpath")), ...
    "SyncOption", SyncOption, ...
    "Remote", remote);